create table image_metadata(id integer primary key autoincrement, name text, title text, text text);
insert into image_metadata values (NULL,'allamericangirl','All American Girl',NULL);
insert into image_metadata values (NULL,'angelbaby','Angel Baby',NULL);
insert into image_metadata values (NULL,'anightinparis','A Night In Paris',NULL);
insert into image_metadata values (NULL,'bathingbeauty','Bathing Beauty',NULL);
insert into image_metadata values (NULL,'birthlovedoll','birthlovedoll',NULL);
insert into image_metadata values (NULL,'blossoming','Blossoming',NULL);
insert into image_metadata values (NULL,'chalkoutline-1','Coppertone',NULL);
insert into image_metadata values (NULL,'chalkoutline-2','Strike a Pose',NULL);
insert into image_metadata values (NULL,'chalkoutline-3','Tantrum',NULL);
insert into image_metadata values (NULL,'contrite','Contrite',NULL);
insert into image_metadata values (NULL,'coppertone','Coppertone',NULL);
insert into image_metadata values (NULL,'cottoncandy','Cotton Candy',NULL);
insert into image_metadata values (NULL,'dollface','Cover Yourself Up, Dollface!',NULL);
insert into image_metadata values (NULL,'drillbabydrill','drillbabydrill',NULL);
insert into image_metadata values (NULL,'envy','Envy',NULL);
insert into image_metadata values (NULL,'flowergirl','Flower Girl',NULL);
insert into image_metadata values (NULL,'giddyup','Giddy Up',NULL);
insert into image_metadata values (NULL,'heymickey','Hey Mickey',NULL);
insert into image_metadata values (NULL,'ilovelove','I Love Love',NULL);
insert into image_metadata values (NULL,'improper','Improper',NULL);
insert into image_metadata values (NULL,'lildebbiedoesdallas','Lil Debbie Does Dallas',NULL);
insert into image_metadata values (NULL,'lolita-1','Lolita 1',NULL);
insert into image_metadata values (NULL,'lolita-2','Lolita 2',NULL);
insert into image_metadata values (NULL,'lolita-3','Lolita 3',NULL);
insert into image_metadata values (NULL,'lolita-4','Lolita 4',NULL);
insert into image_metadata values (NULL,'lolly','Lolly',NULL);
insert into image_metadata values (NULL,'Madonna','madonna',NULL);
insert into image_metadata values (NULL,'masked','Masked',NULL);
insert into image_metadata values (NULL,'milkmustache','Milk Mustache',NULL);
insert into image_metadata values (NULL,'myprincewillcum','My Prince Will Cum',NULL);
insert into image_metadata values (NULL,'naughtyornice','Naughty Or Nice',NULL);
insert into image_metadata values (NULL,'netherland','Netherland',NULL);
insert into image_metadata values (NULL,'oohbaby','Ooh Baby',NULL);
insert into image_metadata values (NULL,'palliative','Palliative',NULL);
insert into image_metadata values (NULL,'palliative','Palliative',NULL);
insert into image_metadata values (NULL,'pigtailsandall','Pigtails and All',NULL);
insert into image_metadata values (NULL,'playinghorsey','Playing Horsey',NULL);
insert into image_metadata values (NULL,'playinghouse','Playing House',NULL);
insert into image_metadata values (NULL,'plushie','Plushie',NULL);
insert into image_metadata values (NULL,'prettyfuckinggrimm-1','Pretty Fucking Grimm #1',NULL);
insert into image_metadata values (NULL,'prettyfuckinggrimm-2','Pretty Fucking Grimm #2',NULL);
insert into image_metadata values (NULL,'prettyfuckinggrimm-3','Pretty Fucking Grimm #3',NULL);
insert into image_metadata values (NULL,'purelove','100% Pure Love',NULL);
insert into image_metadata values (NULL,'pure','Pure',NULL);
insert into image_metadata values (NULL,'ripe','Ripe',NULL);
insert into image_metadata values (NULL,'schoolties','School Ties',NULL);
insert into image_metadata values (NULL,'self_portrait','Self-Portrait as an Inflatable Love Doll',NULL);
insert into image_metadata values (NULL,'sourpuss','Sourpuss',NULL);
insert into image_metadata values (NULL,'staircase','staircase',NULL);
insert into image_metadata values (NULL,'sucker','Sucker',NULL);
insert into image_metadata values (NULL,'suck','Suck',NULL);
insert into image_metadata values (NULL,'suckup','Suck Up',NULL);
insert into image_metadata values (NULL,'switchbox1','switchbox1',NULL);
insert into image_metadata values (NULL,'switchbox2','switchbox2','switchbox1');
insert into image_metadata values (NULL,'switchbox3','switchbox3','switchbox1');
insert into image_metadata values (NULL,'switchbox4','switchbox4','switchbox1');
insert into image_metadata values (NULL,'switchbox5','switchbox5','switchbox1');
insert into image_metadata values (NULL,'teacherspet','Teacher''s Pet',NULL);
insert into image_metadata values (NULL,'theicingonthecake','The Icing on the Cake',NULL);
insert into image_metadata values (NULL,'thor','thor','thor');
insert into image_metadata values (NULL,'thumbsuck','Thumbsuck',NULL);
insert into image_metadata values (NULL,'whatbigeyesyouhave','What Big Eyes You Have',NULL);
insert into image_metadata values (NULL,'wouldyouliketochecksomethingout','Would You Like to Check Something Out?',NULL);
